{"aifont":"OTFEticaDisplay-Thin"	"font-family": 'LFT Etica',"weight": "100","style":""},
{"aifont":"OTFEticaDisplay-ThinItalic"	"font-family": 'LFT Etica',"weight": "100","style": "italic"},
{"aifont":"OTFEtica-Light"	"font-family": 'LFT Etica',"weight": "200","style":""},
{"aifont":"OTFEtica-LightItalic"	"font-family": 'LFT Etica',"weight": "200","style": "italic"},
{"aifont":"OTFEtica-Book"	"font-family": 'LFT Etica',"weight": "300","style":""},
{"aifont":"OTFEtica-BookItalic"	"font-family": 'LFT Etica',"weight": "300","style": "italic"},
{"aifont":"OTFEtica-Regular"	"font-family": 'LFT Etica',"weight": "400","style":""},
{"aifont":"OTFEtica-RegularItalic"	"font-family": 'LFT Etica',"weight": "400","style": "italic"},
{"aifont":"OTFEtica-SemiBold"	"font-family": 'LFT Etica',"weight": "500","style":""},
{"aifont":"OTFEtica-SemiBoldItalic"	"font-family": 'LFT Etica',"weight": "500","style": "italic"},
{"aifont":"OTFEtica-Bold"	"font-family": 'LFT Etica',"weight": "600","style":""},
{"aifont":"OTFEtica-BoldItalic"	"font-family": 'LFT Etica',"weight": "600","style": "italic"},
{"aifont":"OTFEtica-Extrabold"	"font-family": 'LFT Etica',"weight": "bold","style":""},
{"aifont":"OTFEtica-ExtraboldItalic"	"font-family": 'LFT Etica',"weight": "bold","style": "italic"},
{"aifont":"OTFEticaDispla-Heavy"	"font-family": 'LFT Etica',"weight": "800","style":""},
{"aifont":"OTFEticaDisplay-HeavyItalic"	"font-family": 'LFT Etica',"weight": "800","style": "italic"},
{"aifont":"GuardianEgyp-Hairline"	"font-family": 'Guardian Egyptian Web',"weight": "100","style":""},
{"aifont":"GuardianEgyp-Hairline Italic"	"font-family": 'Guardian Egyptian Web',"weight": "100","style": "italic"},
{"aifont":"GuardianEgyp-Thin"	"font-family": 'Guardian Egyptian Web',"weight": "200","style":""},
{"aifont":"GuardianEgyp-ThinIt"	"font-family": 'Guardian Egyptian Web',"weight": "200","style": "italic"},
{"aifont":"GuardianEgyp-Light"	"font-family": 'Guardian Egyptian Web',"weight": "300","style":""},
{"aifont":"GuardianEgyp-LightIt"	"font-family": 'Guardian Egyptian Web',"weight": "300","style": "italic"},
{"aifont":"GuardianEgyp-Regular"	"font-family": 'Guardian Egyptian Web',"weight": "400","style":""},
{"aifont":"GuardianEgyp-RegularIt"	"font-family": 'Guardian Egyptian Web',"weight": "400","style": "italic"},
{"aifont":"GuardianEgyp-Medium"	"font-family": 'Guardian Egyptian Web',"weight": "500","style":""},
{"aifont":"GuardianEgyp-MediumIt"	"font-family": 'Guardian Egyptian Web',"weight": "500","style": "italic"},
{"aifont":"GuardianEgyp-Semibold"	"font-family": 'Guardian Egyptian Web',"weight": "600","style":""},
{"aifont":"GuardianEgyp-SemiboldIt"	"font-family": 'Guardian Egyptian Web',"weight": "600","style": "italic"},
{"aifont":"GuardianEgyp-Bold"	"font-family": 'Guardian Egyptian Web',"weight": "bold","style":""},
{"aifont":"GuardianEgyp-BoldIt"	"font-family": 'Guardian Egyptian Web',"weight": "bold","style": "italic"},
{"aifont":"GuardianEgyp-Black"	"font-family": 'Guardian Egyptian Web',"weight": "800","style":""},
{"aifont":"GuardianEgyp-BlackIt"	"font-family": 'Guardian Egyptian Web',"weight": "800","style": "italic"},
{"aifont":"GuardianTextEgyp-Regular"	"font-family": 'Guardian Text Egyptian Web',"weight": "400","style":""},
{"aifont":"GuardianTextEgyp-RegularIt"	"font-family": 'Guardian Text Egyptian Web',"weight": "400","style": "italic"},
{"aifont":"GuardianTextEgyp-Medium"	"font-family": 'Guardian Text Egyptian Web',"weight": "500","style":""},
{"aifont":"GuardianTextEgyp-MediumIt"	"font-family": 'Guardian Text Egyptian Web',"weight": "500","style": "italic"},
{"aifont":"GuardianTextEgyp-Bold"	"font-family": 'Guardian Text Egyptian Web',"weight": "bold","style":""},
{"aifont":"GuardianTextEgyp-BoldIt"	"font-family": 'Guardian Text Egyptian Web',"weight": "bold","style": "italic"},
{"aifont":"GuardianTextEgyp-Black"	"font-family": 'Guardian Text Egyptian Web',"weight": "900","style":""},
{"aifont":"GuardianTextEgyp-BlackIt"	"font-family": 'Guardian Text Egyptian Web',"weight": "900","style": "italic"},
{"aifont":"Publico Text Roman"	"font-family": 'Publico Text Web',"weight": "400","style":""},
{"aifont":"Publico Text Italic"	"font-family": 'Publico Text Web',"weight": "400","style": "italic"},
{"aifont":"Publico Text Semibold"	"font-family": 'Publico Text Web Semibold',"weight": "600","style":""},
{"aifont":"Publico Text Semibold Italic"	"font-family": 'Publico Text Web Semibold',"weight": "600","style": "italic"},
{"aifont":"Publico Text Bold"	"font-family": 'Publico Text Web',"weight": "bold","style":""},
{"aifont":"Publico Text Bold Italic"	"font-family": 'Publico Text Web',"weight": "bold","style": "italic"},
{"aifont":"Publico Headline Light"	"font-family": 'Publico Headline Web',"weight": "300","style":""},
{"aifont":"Publico Headline Light Italic"	"font-family": 'Publico Headline Web',"weight": "300","style": "italic"},
{"aifont":"Publico Headline Roman"	"font-family": 'Publico Headline Web',"weight": "400","style":""},
{"aifont":"Publico Headline Italic"	"font-family": 'Publico Headline Web',"weight": "400","style": "italic"},
{"aifont":"Publico Headline Medium"	"font-family": 'Publico Headline Web',"weight": "500","style":""},
{"aifont":"Publico Headline Medium Italic"	"font-family": 'Publico Headline Web',"weight": "500","style": "italic"},
{"aifont":"Publico Headline Bold"	"font-family": 'Publico Headline Web',"weight": "bold","style":""},
{"aifont":"Publico Headline Bold Italic"	"font-family": 'Publico Headline Web',"weight": "bold","style": "italic"},
{"aifont":"Publico Headline Extrabold"	"font-family": 'Publico Headline Web',"weight": "800","style":""},
{"aifont":"Publico Headline Extrabold Italic"	"font-family": 'Publico Headline Web',"weight": "800","style": "italic"},
{"aifont":"Publico Headline Black"	"font-family": 'Publico Headline Web',"weight": "900","style":""},
{"aifont":"Publico Headline Black Italic"	"font-family": 'Publico Headline Web',"weight": "900","style": "italic"}
